apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocdtest
spec:
  project: default
  source:
    repoURL: https://github.com/michi-automit/argotest.git
    targetRevision: HEAD
    path: testapp
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
